language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env:
        - PHPCS=true
      script:
        - |
          sed -e 's#^function is_countable(#// &#' -i vendor/giacocorsiglia/wordpress-stubs/wordpress-stubs.php
        - ./vendor/bin/phpstan analyze
        - ./vendor/bin/phpcs
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 7.0
    - php: nightly

install:
  - if [[ $NIGHLTY == true ]]; then composer require "phpunit/phpunit:^8"; fi
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - if [[ $PHPCS == true ]]; then bash <(curl -s https://codecov.io/bash); fi
  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.xml;

notifications:
  email:
    on_success: never
