language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env:
        - COVERAGE=true
        - ./vendor/bin/phpunit --testdox --coverage-clover=coverage.xml
        - ./vendor/bin/phpstan analyze
        - ./vendor/bin/phpcs
    - php: 7.3
    - php: nightly
      env: NIGHLTY=true
  allow_failures:
    - php: 7.0
    - php: nightly

install:
  - composer install
  - if [[ $NIGHLTY == true ]]; then composer require "phpunit/phpunit:^8"; fi

script:
  - ./vendor/bin/phpunit

after_success:
  - if [[ $COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
  - wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.xml;

notifications:
  email:
    on_success: never
